DROP DATABASE IF EXISTS `DOTNET_SERVER`;
CREATE DATABASE IF NOT EXISTS `DOTNET_SERVER`;
USE `DOTNET_SERVER`;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `ITEM`;

CREATE TABLE IF NOT EXISTS `ITEM` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(300) NOT NULL,
    `PRICE` DECIMAL NOT NULL,

    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    `DELETED_AT` DATETIME,
    PRIMARY KEY (`Id`)
);

SET FOREIGN_KEY_CHECKS=1;

DELIMITER $$

CREATE PROCEDURE `DELETE_ITEM` (IN ID BIGINT)
BEGIN
	UPDATE `DOTNET_SERVER`.`ITEM` 
		SET `DOTNET_SERVER`.`ITEM`.`DELETED_AT` = CURRENT_TIMESTAMP()
	WHERE `DOTNET_SERVER`.`ITEM`.`ID` = ID;
END;
